on:
    workflow_dispatch:

jobs:
    alpha-bump:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
      
            - name: Setup git config
              run: |
                git config user.name "GitHub Actions Bot"
                git config user.email "<>"

            - name: Bump alpha version
              run: |
                npm version prerelease --preid=alpha
                git push --follow-tags