name: pull-request
on: 
  pull_request:
    types: 
      - closed
    branches:
      - main
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      -name: Bump version
        run: npm version prerelase preid="alpha"
      - run: |
          echo The PR was merged