name: major-version-release
on: 
  workflow_dispatch:

jobs:
  release-major-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
      - name: Bump version
        run: |
          git pull origin main
          npm version major
          git push

      - name: Echo PR merge
        run: |
          echo ECAS major version updated