name: push
on: 
  push:
    branches:
      - main

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
  
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
      - name: Bump version
        run: |
          npm version prerelease --preid=alpha
          git push
  
      - name: Echo status
        run: |
          echo Version was bumped : )