name: patch-version-release
on: 
  workflow_dispatch:
    inputs:
      type:
        type: choice
        required: true
        default: 'alpha'
        description: Which type of release
        options:
        - alpha
        - patch
        - minor
        - major
        
jobs:
  release-patch-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
      - name: Bump alpha versions
        if: "contains(github.event.inputs.type, 'alpha')"
        run: |
          git pull origin main
          npm version prerelease --preid=${{ github.event.inputs.type }}
          git push
          
      - name: Bump version
        if: "!contains(github.event.inputs.type, 'alpha')"
        run: |
          git pull origin main
          npm version ${{ github.event.inputs.type }}
          git commit --amend -m "${{ github.event.commits[18].message }}"
          git push

      - name: Echo PR merge
        run: |
          echo ECAS patch version updated
